=== unnservice/com.unnsvc.rhena/com.unnsvc.rhena.common/src/main/resources/META-INF/schema/settings.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:rhena:settings" xmlns:tns="urn:rhena:settings" elementFormDefault="qualified">

	<xs:complexType name="repositoryType">
		<xs:attribute name="location" type="xs:anyURI" />
	</xs:complexType>

	<xs:complexType name="repositoryListType">
		<xs:sequence>
			<xs:element name="repository" type="tns:repositoryType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="repositoriesType">
		<xs:sequence>
			<xs:element name="workspace" type="tns:repositoryListType" minOccurs="1" maxOccurs="1" />
			<xs:element name="cache" type="tns:repositoryListType" minOccurs="1" maxOccurs="1" />
			<xs:element name="remote" type="tns:repositoryListType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="dummyType">
		<xs:sequence>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="agentType">
		<xs:sequence>
			<xs:element name="dummy" type="tns:dummyType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="buildType">
		<xs:sequence>
			<xs:element name="dummy" type="tns:dummyType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="repositories" type="tns:repositoriesType" minOccurs="0" maxOccurs="1" />
				<xs:element name="agent" type="tns:agentType" minOccurs="0" maxOccurs="1" />
				<xs:element name="build" type="tns:buildType" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== unnservice/com.unnsvc.rhena/com.unnsvc.rhena.config/src/test/resources/TEST-INF/settings.xml
<?xml version="1.0" encoding="utf-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:rhena:settings" xsi:schemaLocation="urn:rhena:settings http://schema.unnsvc.com/rhena/settings.xsd">
	<repositories>
		<workspace>
			<repository location="file:/home/$USER/noname/.rhena/repository" />
		</workspace>
		<cache>
			<repository location="file:/path" />
		</cache>
		<remote>
			<repository location="http://some/location" />
		</remote>
	</repositories>
</settings>
